/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


float calculadora_prog_1(char *host, float n1, float n2, char op, CLIENT *clnt)
{
	float  *result_1;
	input  soma_1_arg;
	float  *result_2;
	input  sub_1_arg;
	float  *result_3;
	input  mult_1_arg;
	float  *result_4;
	input  div_1_arg;
	
	// OPERAÇÃO DE SOMA:
	if (op == '+') {
		soma_1_arg.n1 = n1;
		soma_1_arg.n2 = n2;
		soma_1_arg.op = op;

		result_1 = soma_1(&soma_1_arg, clnt);
		if (result_1 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		return *result_1;
	}
	// OPERAÇÃO DE SUBTRAÇÃO:
	else if (op == '-') {
		sub_1_arg.n1 = n1;
		sub_1_arg.n2 = n2;
		sub_1_arg.op = op;

		result_2 = sub_1(&sub_1_arg, clnt);
		if (result_2 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		return *result_2;
	}
	// OPERAÇÃO DE MULTIPLICAÇÃO:
	else if (op == '*') {
		mult_1_arg.n1 = n1;
		mult_1_arg.n2 = n2;
		mult_1_arg.op = op;

		result_3 = mult_1(&mult_1_arg, clnt);
		if (result_3 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		return *result_3;
	}
	// OPERAÇÃO DE DIVISÃO:
	else if (op == '/') {
		div_1_arg.n1 = n1;
		div_1_arg.n2 = n2;
		div_1_arg.op = op;

		if (n2 == 0) {
			printf("Divisão por zero não é válida.\n");
			exit (0);
		}
		else {
			result_4 = div_1(&div_1_arg, clnt);
			if (result_4 == (float *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			return *result_4;
		}
	}
}

int main (int argc, char *argv[])
{
	char *host;
	float a,b;
	char op;
	CLIENT *clnt;

	if (argc < 2) {
	printf ("usage: %s server_host\n", argv[0]);
	exit (1);
	}

	host = argv[1];

	clnt = clnt_create (host, CALCULADORA_PROG, CALCULADORA_VERSION, "udp");

	if (clnt == NULL) {
	clnt_pcreateerror (host);
	exit (1);
	}

	printf("\n--== CALCULADORA RPC ==--\n\n");
	printf("LISTA DE OPERAÇÕES:\n");
	printf("SOMA (+)\nSUBTRAÇÃO (-)\nMULTIPLICAÇÃO (*)\nDIVISÃO (/)\n");
	printf("-------------------------\n");
	printf("PARA SAIR INSIRA 'x' NO CÓDIGO DE OPERAÇÃO\n\n");
	while (1) {
		printf("Insira o primeiro número:\n");
		scanf("%f",&a);
		printf("Insira o segundo número\n");
		scanf("%f",&b);
		printf("Insira o caractere correspondente a uma das operações:\n");
		scanf("%s",&op);
		
		if (op == 'x') break;
		printf("Resposta: %f\n",calculadora_prog_1 (host,a,b,op,clnt));
	}

	clnt_destroy (clnt);

	exit (0);
}
