/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct input {
	float n1;
	float n2;
	char op;
};
typedef struct input input;

#define CALCULADORA_PROG 0x2fffffff
#define CALCULADORA_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define soma 1
extern  float * soma_1(input *, CLIENT *);
extern  float * soma_1_svc(input *, struct svc_req *);
#define sub 2
extern  float * sub_1(input *, CLIENT *);
extern  float * sub_1_svc(input *, struct svc_req *);
#define mult 3
extern  float * mult_1(input *, CLIENT *);
extern  float * mult_1_svc(input *, struct svc_req *);
#define div 4
extern  float * div_1(input *, CLIENT *);
extern  float * div_1_svc(input *, struct svc_req *);
extern int calculadora_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define soma 1
extern  float * soma_1();
extern  float * soma_1_svc();
#define sub 2
extern  float * sub_1();
extern  float * sub_1_svc();
#define mult 3
extern  float * mult_1();
extern  float * mult_1_svc();
#define div 4
extern  float * div_1();
extern  float * div_1_svc();
extern int calculadora_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input (XDR *, input*);

#else /* K&R C */
extern bool_t xdr_input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
